package com.rinne.shared.network.model.sync

import com.rinne.shared.network.model.error.NetworkApiError
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

// The offline sync protocol. Design: rinne-backend-redesigned/docs/design/offline-sync.md.
// Cursors are opaque strings: store them as received and send them back unchanged.

/** `POST /api/v1/sync/status` — the device's cursor per space it has data for. */
@Serializable
data class NetworkSyncStatusRequest(
    val cursors: Map<String, String> = emptyMap(),
)

@Serializable
data class NetworkSyncStatus(
    /** Every space the user can access. */
    val spaces: List<NetworkSyncSpace>,
    /** Spaces the device sent a cursor for but can no longer access: delete their local data. */
    val removedSpaces: List<String>,
)

@Serializable
data class NetworkSyncSpace(
    val id: String,
    val kind: NetworkSpaceKind,
    val role: NetworkSpaceRole,
    /** Something changed above the device's cursor (always true without a cursor): pull it. */
    val changed: Boolean,
)

@Serializable
enum class NetworkSpaceKind {
    @SerialName("personal") Personal,
    @SerialName("shared") Shared,
}

@Serializable
enum class NetworkSpaceRole {
    @SerialName("owner") Owner,
    @SerialName("editor") Editor,
    @SerialName("viewer") Viewer,
}

/** `POST /api/v1/sync/pull` — changes of one space after [cursor]; `null` downloads it from scratch. */
@Serializable
data class NetworkSyncPullRequest(
    val spaceId: String,
    val cursor: String? = null,
    val limit: Int? = null,
)

@Serializable
data class NetworkSyncPullResponse(
    /** Ordered; apply them in this order. */
    val changes: List<NetworkSyncChange>,
    /** Save it together with the applied changes and send it in the next pull of this space. */
    val cursor: String,
    /** More changes are waiting: pull again with [cursor]. */
    val hasMore: Boolean,
)

@Serializable
data class NetworkSyncChange(
    /** Entity type, e.g. `note`; see the `SyncType` constant of each entity DTO. */
    val type: String,
    val id: String,
    /** Base version for the device's next edit of this entity. */
    val version: Long,
    val op: NetworkSyncOp,
    /** The entity's current state (its DTO) for [NetworkSyncOp.Upsert]; absent for deletes. */
    val entity: JsonObject? = null,
)

@Serializable
enum class NetworkSyncOp {
    /** Created or changed: insert or replace the local copy. */
    @SerialName("upsert") Upsert,

    /** Deleted: remove the local copy (ignore if the device doesn't have it). */
    @SerialName("delete") Delete,
}

/** `POST /api/v1/sync/push` — applied in order; at most 500 mutations per request. */
@Serializable
data class NetworkSyncPushRequest(
    val mutations: List<NetworkSyncMutation>,
)

@Serializable
data class NetworkSyncMutation(
    /** Unique per mutation (UUIDv7); a retried mutation with the same id is applied only once. */
    val mutationId: String,
    val spaceId: String,
    val type: String,
    val op: NetworkSyncOp,
    /** The entity id, generated by the device (UUIDv7) when it created the entity. */
    val id: String,
    /** The entity version the device last saw; `null` for an entity the device created. */
    val baseVersion: Long? = null,
    /**
     * Changed fields only, named like the entity DTO's properties: an absent key is unchanged,
     * `null` clears the field. Ignored for deletes.
     */
    val fields: JsonObject = JsonObject(emptyMap()),
)

@Serializable
data class NetworkSyncPushResponse(
    /** One per mutation, in request order. */
    val results: List<NetworkSyncMutationResult>,
)

@Serializable
data class NetworkSyncMutationResult(
    val mutationId: String,
    val status: NetworkSyncMutationStatus,
    /** The entity's new version (applied changes). */
    val version: Long? = null,
    /** The edit brought back an entity deleted elsewhere. */
    val restored: Boolean = false,
    /** Fields changed elsewhere since the base version and overwritten by this mutation. */
    val conflicts: List<NetworkSyncFieldConflict> = emptyList(),
    /** Why a mutation was skipped, e.g. `edited_elsewhere`. */
    val reason: String? = null,
    /** Why a mutation was rejected or failed. */
    val error: NetworkApiError? = null,
)

@Serializable
enum class NetworkSyncMutationStatus {
    /** Done; drop it from the outbox. */
    @SerialName("applied") Applied,

    /** Intentionally not applied (see `reason`); drop it, the next pull brings the server state. */
    @SerialName("skipped") Skipped,

    /**
     * Permanently refused (validation, unknown entity, no permission, see `error`); drop it and
     * surface it. `sync.entity_gone`: re-send the entity as a create with all fields.
     */
    @SerialName("rejected") Rejected,

    /** The server failed unexpectedly; keep it in the outbox and retry later. */
    @SerialName("error") Error,
}

@Serializable
data class NetworkSyncFieldConflict(
    val field: String,
    /** The value this mutation overwrote. */
    val overwrittenValue: JsonElement,
)
